# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"\x1f\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"0\n\x0c\x41uthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x0b\x43hatMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\x19\n\x08UserList\x12\r\n\x05users\x18\x01 \x03(\t2p\n\x0b\x41uthService\x12\x31\n\x08Register\x12\x11.chat.AuthRequest\x1a\x12.chat.AuthResponse\x12.\n\x05Login\x12\x11.chat.AuthRequest\x1a\x12.chat.AuthResponse2<\n\x0bUserService\x12-\n\x0eGetOnlineUsers\x12\x0b.chat.Empty\x1a\x0e.chat.UserList2E\n\x0b\x43hatService\x12\x36\n\nChatStream\x12\x11.chat.ChatMessage\x1a\x11.chat.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=20
  _globals['_AUTHREQUEST']._serialized_end=51
  _globals['_AUTHRESPONSE']._serialized_start=53
  _globals['_AUTHRESPONSE']._serialized_end=101
  _globals['_CHATMESSAGE']._serialized_start=103
  _globals['_CHATMESSAGE']._serialized_end=151
  _globals['_EMPTY']._serialized_start=153
  _globals['_EMPTY']._serialized_end=160
  _globals['_USERLIST']._serialized_start=162
  _globals['_USERLIST']._serialized_end=187
  _globals['_AUTHSERVICE']._serialized_start=189
  _globals['_AUTHSERVICE']._serialized_end=301
  _globals['_USERSERVICE']._serialized_start=303
  _globals['_USERSERVICE']._serialized_end=363
  _globals['_CHATSERVICE']._serialized_start=365
  _globals['_CHATSERVICE']._serialized_end=434
# @@protoc_insertion_point(module_scope)
